include:
  - project: 2-dast-2-continuos/templates
    file: ZAP.gitlab-ci.yml
    ref: master
  - project: 2-dast-2-continuos/templates
    file: ARACHNI.gitlab-ci.yml
    ref: master

include:
  - project: 2-dast-2-continuos/templates
    file: ZAP.gitlab-ci.yml
    ref: master

build_image:
  extends:
    - .analyze_zap
  variables:
    ZAP_WEBSITE: http://23.102.130.177/index.html#!/
  stage: zap_analysis
  only: 
    - test-zap
    - master
    
arachni:
  extends:
    - .analyze_arachni
  stage:
    arachni_analysis
  variables:
    AR_URL: "http://23.102.130.177/index.html#!/"
